# Generated by Django 6.0.2 on 2026-02-19 12:57

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={"unique": "A user with that username already exists."},
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name="username",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=150, verbose_name="first name")),
                ("last_name", models.CharField(blank=True, max_length=150, verbose_name="last name")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="email address")),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                ("date_joined", models.DateTimeField(default=django.utils.timezone.now, verbose_name="date joined")),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, help_text="Timestamp when the record was soft-deleted", null=True
                    ),
                ),
                (
                    "ktp_number",
                    models.CharField(
                        help_text="Indonesian ID number (KTP) - 16 digits",
                        max_length=16,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="KTP number must be exactly 16 digits.", regex="^\\d{16}$"
                            )
                        ],
                        verbose_name="KTP Number",
                    ),
                ),
                ("date_of_birth", models.DateField(help_text="User's date of birth", verbose_name="Date of Birth")),
                ("address", models.TextField(help_text="User's complete address")),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Indonesian phone number (accepts +62, 62, or 0 prefix)",
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must start with +62, 62, or 0 followed by 9-13 digits.",
                                regex="^(?:\\+62|62|0)\\d{9,13}$",
                            )
                        ],
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "ordering": ["-date_joined"],
                "indexes": [models.Index(fields=["last_name", "first_name"], name="user_user_last_na_2080cc_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("ktp_number",),
                        name="unique_ktp_when_not_deleted",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("email",),
                        name="unique_email_when_not_deleted",
                    ),
                ],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
