# Generated by Django 6.0.2 on 2026-02-25 18:58

import django.core.validators
import modules.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", modules.user.models.SoftDeleteUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                help_text="Indonesian phone number (accepts +62, 62, or 0 prefix)",
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must start with +62, 62, or 0 followed by 9-13 digits.",
                        regex="^(?:\\+62|62|0)[0-9\\s\\-]{9,15}$",
                    )
                ],
            ),
        ),
    ]
